### ISSUE TITLE
support private packages

### ISSUE THREAD

**Issue by dickeyxxx** [dickeyxxx/npm-register#1]
Originally this project was needed to ensure that only authenticated users could publish packages, but they needed to be installable by anyone. For most projects, however, you would want only authenticated users to be able to publish or install packages.

This will have to be a configurable option.

**Comment by zeke** [comment]
I'm watching this repo :)

**Comment by dickeyxxx** [comment]
this is actively used! https://heroku-npm.herokuapp.com/package-json-to-readme

**Comment by raulb** [comment]
Hi @zeke :wave:

**Comment by zeke** [comment]
:raised_hands:

**Comment by resistdesign** [comment]
:+1:

**Comment by dickeyxxx** [comment]
I've got an idea how to make this work and still have the CDN stuff. Hopefully I'll get some time to work on it soon-ish.

**Comment by ealves-pt** [comment]
@dickeyxxx I don't know what is your plan but it would be nice that we could manage organizations, teams and users with it.

**Comment by dickeyxxx** [comment]
#1 would certainly have to come first

**Comment by danielo515** [comment]
I'm confused about this, are the published packages publicly available? There is no way to make them private?

**Comment by milankinen** [comment]
Hi @dickeyxxx!

I could make a PR making read/write auth configurable if it's ok for you. In my implementation there would be two environment variables:

* `AUTH_WRITE=true|false` (defaults `true`)
    * All `post/put/delete` routes except `auth`
* `AUTH_READ=true|false` (defaults `false`)
    * All `get` routes except `index` and `auth`

`auth` route authentication would remain as it is (non-configurable)

Thoughts?

**Comment by dickeyxxx** [comment]
@milankinen that sounds reasonable, but maybe prefix the var with `NPM_REGISTER_*` so they won't conflict with anything else

**Comment by milankinen** [comment]
@dickeyxxx Absolutely! 👍

**Comment by danielo515** [comment]
What is the state of this? I would love to use this in production,but I need packages to be totally private .

Regards

**Comment by milankinen** [comment]
Sorry I had other pending tasks I had to finish first, but here is my first try: #62
