### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by okeydoke** [dickeyxxx/npm-register#19]
Hey there, 

I'm trying to authenticate on the elephant register so I can publish a private package but getting the following error:
```
npm login --registry http://<IP_ADDRESS>
---
npm WARN adduser Incorrect username or password
npm WARN adduser You can reset your account by visiting:
npm WARN adduser
npm WARN adduser     https://npmjs.org/forgot
npm WARN adduser
npm ERR! Windows_NT 10.0.14366
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "login" "--registry" "http://<IP_ADDRESS>"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code E401

npm ERR! invalid credentials : -/user/org.couchdb.user:<user>
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\npm-debug.log
```

I tried a using my NPM account as well as creating a new one via `npm adduser --registry http://<IP_ADDRESS>` but that also fails with same error. Any ideas whats going wrong? 
Thanks!

**Comment by dickeyxxx** [comment]
`adduser` doesn't do what you think it does, it's just an alias for `login`. Read the instructions in the README, it explains how to setup accounts.

**Comment by okeydoke** [comment]
Oh right my bad! I totally skipped over the S3 htpasswd part of authentication

**Comment by dickeyxxx** [comment]
potentially we could make the authentication disableable if you're in a kind of environment that makes it unneeded

**Comment by okeydoke** [comment]
Actually that would be quite good.
