### ISSUE TITLE
How are packages stored?

### ISSUE THREAD

**Issue by zeke** [dickeyxxx/npm-register#30]
I got this thing working! So hard to set up S3 credentials. :scream:

I see the packages pouring in:

![screen shot 2016-08-21 at 5 37 55 pm](https://cloud.githubusercontent.com/assets/2289/17840894/403e9bf2-67c6-11e6-8c6e-ecd69c039b44.png)

I don't see any version info, though. How are different versions of the same package cached?

**Comment by zeke** [comment]
> How is babby formed?

**Comment by okeydoke** [comment]
If you look in the `tarballs` 'folder' the different version are in there

**Comment by dickeyxxx** [comment]
You're looking at the metadata for packages, of which there is only one. The tarballs are stored in `/tarballs`.

**Comment by zeke** [comment]
Cool. Thanks.
