### ISSUE TITLE
Published packages fail to download eventually

### ISSUE THREAD

**Issue by okeydoke** [dickeyxxx/npm-register#32]
After some amount of time (not sure exactly, maybe a day or so) packages that have been published fail to be downloaded. Is there some form of caching/mapping that is expiring? maybe redis? The files are being stored in S3 and there is a corresponding version tarball on the bucket.
The example below is for a scoped package but also had the issue with non-scoped packages.
```
$ npm install
npm ERR! fetch failed http://private-registry/@scope/pacakage/-/@scope/package-0.0.3/e4e40cc32eeaf250a9353243f3f6863fc7813331.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

Only solution I have found is to bump version and republish and then it starts to work again for awhile

**Comment by dickeyxxx** [comment]
does the package also exist on npm? or only in your registry?

**Comment by okeydoke** [comment]
Only in my registry

**Comment by dickeyxxx** [comment]
It doesn't use the cache for the tarballs at all, it pretty much just tries to fetch the file out of s3. Is the tarball in s3? I'm putting a log line in right now that will say `Fetching...` when it attempts to grab something out of s3.

**Comment by dickeyxxx** [comment]
grab the latest `HEAD` version of this, that has the logging message

**Comment by dickeyxxx** [comment]
FYI I haven't seen this happen before, and it definitely would be a major problem for us. Maybe it's s3 permissions or something?

**Comment by okeydoke** [comment]
Hmm yeah it doesn't seem to be `Fetching` the published package. It fetches all the other ones and then looking at the log, get a 404 at 
```
measure#request=0ms method=GET user-agent="npm/3.9.5 node/v6.2.2 win32 x64" status=404 path=/@scope/package/-/@scope/package-0.0.3/e4e40cc32eeaf250a9353243f3f6863fc7813331.tgz request_id=0.17862000812639067
measure#request=2ms method=GET user-agent="npm/3.9.5 node/v6.2.2 win32 x64" status=404 path=/@scope/package/-/@scope/package-0.0.3/e4e40cc32eeaf250a9353243f3f6863fc7813331.tgz request_id=0.01216173275852217
```

**Comment by dickeyxxx** [comment]
I think this might be something related to scoped packages then. There are no conditionals on that route that I can see that would do anything other than showing that message.

**Comment by dickeyxxx** [comment]
Come to think of it, I'm not sure I ever actually tested publishing scoped packages.

**Comment by okeydoke** [comment]
It's weird, cos it works for awhile

**Comment by dickeyxxx** [comment]
it might be client-side caching

**Comment by okeydoke** [comment]
Okay I think I know what the issue is. https://github.com/dickeyxxx/npm-register/blob/master/routes/tarballs.js#L36 doesn't actually match the path that is being provided when using a @scoped package

```js
r.get('/:scope/:name/-/:filename/:sha', tarball)
```
changing to the following removes the 404 error
```js
r.get('/:scope/:name/-/*/:filename/:sha', tarball)
```

But now getting a checksum error

**Comment by dickeyxxx** [comment]
try the latest `HEAD`, I put a patch in for this

**Comment by okeydoke** [comment]
AH ok, actually can't test off HEAD on the environment we've set up since its installed via npm. Guessing haven't published recently?

**Comment by dickeyxxx** [comment]
you can install from github, just do `npm install dickeyxxx/npm-register`

**Comment by okeydoke** [comment]
Hmm doesn't seem to be working with PM2 after updating on the vm we're running it on

**Comment by okeydoke** [comment]
Had to revert back to npm registry installed package

**Comment by dickeyxxx** [comment]
what error are you getting? I have an idea what it might be, but without an error it's hard to know.

**Comment by okeydoke** [comment]
I think the issue is running `server.js` didn't actually start the server

**Comment by dickeyxxx** [comment]
use start.js instead

**Comment by dickeyxxx** [comment]
or better yet `npm start`

**Comment by okeydoke** [comment]
Ok thanks, that works
