### ISSUE TITLE
Release v2.0.3

### ISSUE THREAD

**Issue by ealves-pt** [dickeyxxx/npm-register#38]
@dickeyxxx could you release a new version with the latest PR that I've made? I kinda need that :P

**Comment by okeydoke** [comment]
Yeah also would like the new changes in a release.
I dont think a minor point release is right though, its has breaking changes in it

**Comment by dickeyxxx** [comment]
it might take me a while to get around to testing this and everything, for now just install from github

**Comment by okeydoke** [comment]
Hmm don't really want to be installing from master as part of an automated step

**Comment by dickeyxxx** [comment]
Just do `npm i dickeyxxx/npm-register#13902fdfe0c8faf6ed1fd3b853aae2862bd9b1c2`. It's literally the same thing as if I were to cut a release.
