### ISSUE TITLE
Does not support npm upgrade

### ISSUE THREAD

**Issue by haakonnessjoen** [dickeyxxx/npm-register#75]
Hey,

Nice module, but this module has the same problem as sinopia. It does not handle npm upgrade correctly.

Lets say i publish myapp@1.0.1 and then later i upload myapp@1.0.2.

If i do a npm upgrade in a package that has a myapp dependency, it does not think there is a newer version. Maybe you are not generating etag using info from latest package.json file.

**Comment by dickeyxxx** [comment]
well it does cache for about 15 minutes so you might be running into that

**Comment by dickeyxxx** [comment]
going to need more information if you think there is a problem, we don't see issues using `npm upgrade`

**Comment by haakonnessjoen** [comment]
Sorry, I got it to work now. I had specified the absolute version of the package in the dependencies section. I was sure it was '*'.
